### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by AndyHaas** [ringcentral/ringcentral-web-widget#31]
Is there a way we can have the widget auto renew the session so that the widget always stay logged in?

**Comment by embbnux** [comment]
Hi, @AndyHaas If you want to have it auto renew the session, you need to use authorization code flow to auth instead of implicit grant flow. So you need to provide ['appSecret'](https://github.com/ringcentral/ringcentral-web-widget#create-api-secret-file-in-project-root-path) to this app. In authorization code flow, it will renew the token automatically. But if the app disconnect network from server for a long time, the session will timeout.

**Comment by AndyHaas** [comment]
@embbnux am I able to add appSecret to the src on the iFrame?
